stages:
  - build

variables:
  IMAGE_NAME: my-docker-image

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME .
    - docker run $IMAGE_NAME
  only:
    - main
